### ISSUE TITLE
Empty page error rendering case list

### ISSUE THREAD

**Issue by mbarton** [rcpch/rcpch-audit-engine#840]
Exception from the production logs:

```
ERROR [django.request] Internal Server Error: /organisation/86/cases/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/epilepsy12/decorator.py", line 378, in wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/epilepsy12/decorator.py", line 184, in wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/epilepsy12/views/case_views.py", line 286, in case_list
    case_list = paginator.page(page_number)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/paginator.py", line 72, in page
    number = self.validate_number(number)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/paginator.py", line 54, in validate_number
    raise EmptyPage(_("That page contains no results"))
django.core.paginator.EmptyPage: That page contains no results
```

Also affected organisation 287.

**Comment by eatyourpeas** [comment]
This one may be tricky to get to the bottom of. I have checked in both organisations in production and the pagination buttons seem to be working as expected. There was a previous issue where the pagination buttons on click would lose the filter parameter and that fix still seems to be working. I have not been able to replicate in development either. Perhaps we could think about this together on a call some time?

**Comment by mbarton** [comment]
Yep sounds good - we can check the logs again and see if it has recurred

**Comment by mbarton** [comment]
Check in the logs it's fixed (Should be fixed by https://github.com/rcpch/rcpch-audit-engine/pull/951)
